<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginForm</name>
   <tag></tag>
   <elementGuidId>9b866b94-1d98-467f-8839-f38b672ac0a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-form</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
